source :rubygems
gem 'sinatra',         '1.4.3'
gem 'sinatra-contrib', '1.4.1'
gem 'unicorn',         '4.6.3'
gem 'json',            '1.8.0'
gem 'mysql2',          '0.3.13'
gem 'mysql2-cs-bind',  '0.0.6'
gem 'uuid',            '2.3.7'
gem "hiredis", "~> 0.4.0"
gem "redis", ">= 2.2.0", :require => ["redis", "redis/connection/hiredis"]
# gem "redis", "~> 3.0.1"
# gem "hiredis", "~> 0.4.5"

group :development do
  # run "bundle exec shotgun" on development
  gem 'shotgun'
end
